# python train.py --c config/classic_cv_imb/fixmatch/softmatch_cifar100_lb1500_100_ulb3000_100_0.yaml
algorithm: softmatch
save_dir: ./saved_models
save_name: bidmatch_cifar100_lb1500_100_ulb3000_100_0
resume: True
load_path: ./saved_models/bidmatch_cifar100_lb1500_100_ulb3000_100_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_log_iter: 256
num_labels: 150
batch_size: 64
eval_batch_size: 256
hard_label: True
dist_align: True
dist_uniform: True
ema_p: 0.999
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data/data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10133
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
lb_imb_ratio: 100
ulb_imb_ratio: 100
ulb_num_labels: 300
